site_name: Vespucci 
site_dir: /var/www/site
site_description: 'Main site for Vespucci the Android OpenStreetMap Editor'
theme_dir: 'flatly-custom'
pages:
- Home: 'index.md'
- Introduction: 
    - 'Introduction': 'markdown/en/Introduction.md'
    - '0.9.7 Release notes': 'markdown/en/0.9.7 Release notes.md'
    - '0.9.6 Release notes': 'markdown/en/0.9.6 Release notes.md'
- Editing: 
    - 'Main map display': 'markdown/en/Main map display.md'
    - 'Creating new objects': 'markdown/en/Creating new objects.md'
    - 'Node selected': 'markdown/en/Node selected.md'
    - 'Way selected': 'markdown/en/Way selected.md'
    - 'Relation selected': 'markdown/en/Relation selected.md'
    - 'Property editor': 'markdown/en/Property editor.md'
    - 'Multiselect': 'markdown/en/Multiselect.md'
    - 'Conflict resolution': 'markdown/en/Conflict resolution.md'
- Advanced topics:
    - 'Presets': 'markdown/en/Presets.md' 
    - 'Aligning background imagery': 'markdown/en/Aligning background imagery.md'
    - 'Keyboard and mouse': 'markdown/en/Keyboard.md'  
    - 'GPS sources': 'markdown/en/GPS sources.md'           
- Tutorials and Posts:
    - 'Using name suggestions': 'markdown/tutorials/name_suggestions.md'
    - 'Reporting Vespucci issues': 'markdown/tutorials/reporting_issues.md'
    - 'Tag-only editing':  'markdown/tutorials/tag_only.md'
- Screenshots: 'markdown/tutorials/screenshots.md'
- FAQ: 'markdown/tutorials/faq.md'
