site_name: Vespucci 
site_dir: /var/www/site
site_description: 'Main site for Vespucci the Android OpenStreetMap Editor'
theme:
  name: flatly
  custom_dir: flatly-custom
  favicon: favicon.ico
extra:
  version: 11.0.0
  project: Vespucci
pages:
- Vespucci: 'index.md'
- Introduction: 
    - 'Introduction': 'help/en/Introduction.md'
    - '11.0.0 Release notes': 'help/en/11.0.0 Release notes.md'
    - '10.2.0 Release notes': 'help/en/10.2.0 Release notes.md'
    - '10.1.0 Release notes': 'help/en/10.1.0 Release notes.md'
    - '10.0.0 Release notes': 'help/en/10.0.0 Release notes.md'
    - '0.9.9 Release notes': 'help/en/0.9.9 Release notes.md'
    - '0.9.8 Release notes': 'help/en/0.9.8 Release notes.md'
    - '0.9.7 Release notes': 'help/en/0.9.7 Release notes.md'
    - '0.9.6 Release notes': 'help/en/0.9.6 Release notes.md'
    - 'Previous release notes': 'tutorials/old_release_notes.md'
- Editing: 
    - 'Main map display': 'help/en/Main map display.md'
    - 'Creating new objects': 'help/en/Creating new objects.md'
    - 'Node selected': 'help/en/Node selected.md'
    - 'Way selected': 'help/en/Way selected.md'
    - 'Relation selected': 'help/en/Relation selected.md'
    - 'Property editor': 'help/en/Property editor.md'
    - 'Multiselect': 'help/en/Multiselect.md'
    - 'Conflict resolution': 'help/en/Conflict resolution.md'
    - 'Presets': 'help/en/Presets.md' 
    - 'Aligning background imagery': 'help/en/Aligning background imagery.md'
    - 'Keyboard and mouse': 'help/en/Keyboard.md'  
    - 'GPS sources': 'help/en/GPS sources.md'
    - 'Tag based filter': 'help/en/Tag filter.md'
    - 'Preset based filter': 'help/en/Preset filter.md'
    - 'Opening hours': 'help/en/Opening hours.md'
    - 'Preferences': 'help/en/Preferences.md'
    - 'Advanced preferences': 'help/en/Advanced preferences.md'           
- Tutorials and Posts:
    - '"network" Location Provider Support': 'tutorials/network_location.md'
    - 'Custom imagery': 'tutorials/custom_imagery.md'
    - 'Using name suggestions': 'tutorials/name_suggestions.md'
    - 'Reporting Vespucci issues': 'tutorials/reporting_issues.md'
    - 'Tag-only editing':  'tutorials/tag_only.md'
    - 'Vespucci presets': 'tutorials/presets.md'
    - 'Controlling Vespucci from other apps': 'tutorials/vespucci_intents.md'
- Screenshots: 'tutorials/screenshots.md'
- FAQ: 'tutorials/faq.md'
- Privacy: 'help/en/Privacy.md'
