name: Android CI

on:
  push:
    branches:
    - master
    - tree/*MAINT
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Copy dummy keys2.txt
      shell: bash
      run: |
         mkdir -p $GITHUB_WORKSPACE/../private_assets
         cp $GITHUB_WORKSPACE/src/test/resources/keys2.txt $GITHUB_WORKSPACE/../private_assets
    - name: Build with Gradle
      run: ./gradlew assembleCurrentDebug
    - name: Run unit tests
      timeout-minutes: 15
      run: ./gradlew testCurrentDebugUnitTest
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
         name: Test output
         path: $GITHUB_WORKSPACE/build/reports/tests/testCurrentDebugUnitTest/
#    - name: Run lint
#      run: ./gradlew lint
